### ISSUE TITLE
New article link is broken

### ISSUE THREAD

**Issue by Benjozork** [blogify-dev/blogify#10]
~~Broken by dd8c6d9395bc09266b8a60593bdfc97dd806c120~~

~~Needs fix~~

Fixed in 354e5e7556253492f00ad06a7a1d1f8d1ab56ba9

New issue: The new article button along with profile button doesn't show the hand thingy on hover. This is due to them using a function called on click event to navigate instead of `routerLink`

Needs fix

**Comment by hamza1311** [comment]
Fixed and updated the issue

**Comment by Benjozork** [comment]
Solution : 
```css
cursor: pointer;
```
