### ISSUE TITLE
Add comment likes

### ISSUE THREAD

**Issue by Benjozork** [blogify-dev/blogify#33]
Self-explanatory.

**Comment by hamza1311** [comment]
Implement backend in d2fb2b718639285d9c873d040e205ce224184b36 with further improvements in a0afeb144276bf4b6fdea1721958bc8f69df38b8

**Comment by Benjozork** [comment]
Further improvements to frontend in ea2060e15de1708c375132709ed888ddba81adbe

**Comment by Benjozork** [comment]
Pretty much done.
