### ISSUE TITLE
Complete comment tree mechanics

### ISSUE THREAD

**Issue by Benjozork** [blogify-dev/blogify#6]
- Context (chain from top-level comment)
- Subtree
- Tree API (depth, origin...)

**Comment by hamza1311** [comment]
How much of it is completed after https://github.com/Benjozork/blogify/commit/488e6beb4b77e35941f1518c82eb6dd370cf0c30 and what's left to do for comments tree??

**Comment by Benjozork** [comment]
> How much of it is completed after [488e6be](https://github.com/Benjozork/blogify/commit/488e6beb4b77e35941f1518c82eb6dd370cf0c30) and what's left to do for comments tree??

 - Context (chain from top-level comment)
 - Subtree
 - Tree API (depth, origin...)

**Comment by Benjozork** [comment]
Done.
