### ISSUE TITLE
/api/articles/content runs 5 queries for every request

### ISSUE THREAD

**Issue by Benjozork** [blogify-dev/blogify#9]
![image](https://user-images.githubusercontent.com/4503241/64922624-3de99180-d79f-11e9-8fbd-766bfe544d65.png)

1) Article fetch;
2) User fetch (password shouldn't be SELECT-ed, but that's another issue);
3) Content fetch (even if the whole thing is inefficient, this shouldn't be happening);
4) Categories fetch;
5) Content fetch again;
6) Respond with last content fetch;

**Comment by Benjozork** [comment]
Here's the issue :

https://github.com/blogify-dev/blogify/blob/968eedcc269206042a3e0439eebe5f7bfea189f3/src/blogify/backend/routes/articles/ContentRoutes.kt#L16

1) handleResourceFetch will fetch the article using the first function

https://github.com/blogify-dev/blogify/blob/968eedcc269206042a3e0439eebe5f7bfea189f3/src/blogify/backend/services/articles/ArticleService.kt#L27

calls ->

https://github.com/blogify-dev/blogify/blob/968eedcc269206042a3e0439eebe5f7bfea189f3/src/blogify/backend/services/handling/Handlers.kt#L38-L53

calls ->

https://github.com/blogify-dev/blogify/blob/968eedcc269206042a3e0439eebe5f7bfea189f3/src/blogify/backend/database/Tables.kt#L37-L48

2) handleResourceFetch will run the second function on the result of the first

https://github.com/blogify-dev/blogify/blob/968eedcc269206042a3e0439eebe5f7bfea189f3/src/blogify/backend/resources/Article.kt#L55-L59

### Design problem

* Directly fetch content from the database
  * This can't be wrapped into `handleResourceFetch`, because `Article.Content` doesn't extend `Resource`, therefore it has no associated `Service`
  * This is a fundamental design problem; weak, Resource-associated entities are not handled by function wrappers and have to be treated as second-class citizens

### Possible solution

* Introduce a super-type of `Resource` that is not identified by an UUID. Rename current `Resource` to `IdentifiedResource` and create a sibling type named `WeakResource` that only lives when associated to another `IdentifiedResource`
* Modify every function wrapper that takes a current `Resource` to take any of it's super-type, where possible.

**Comment by hamza1311** [comment]
Removed Article.Content and as a result, `/api/articles/content` in https://github.com/blogify-dev/blogify/commit/8bd2bbc36d5b0133094c3dbc159e01a1cbbe289a in favor of a better and more efficient solution. Article content is now also provided by `/api/articles/{uuid}`, which returns the whole object. If only content is required, `/api/articles/{uuid}/?fields=content` can be used.

Issue fixed
